ALTER TABLE stages
ADD COLUMN rounds INTEGER,
ADD COLUMN points_win INTEGER DEFAULT 3 NOT NULL,
ADD COLUMN points_draw INTEGER DEFAULT 1 NOT NULL,
ADD COLUMN points_loss INTEGER DEFAULT 0 NOT NULL,
ADD COLUMN overtime_enabled BOOLEAN DEFAULT false NOT NULL,
ADD COLUMN seeded BOOLEAN DEFAULT false NOT NULL,
ADD COLUMN generated BOOLEAN DEFAULT false NOT NULL;